# Site
title: affilinet Developer Hub
subtitle: Tools for an easy integration with affilinet for publishers and advertisers
meta_description: Find documentation and download for all affilinet Developer tools
url: https://affilinet.github.io

mainmenu: 
  - slug: publisher
    title: Publisher
  - slug: advertiser
    title: Advertiser

# Conversion
markdown: kramdown
highlighter: rouge
permalink: date

# Collections
collections:
  advertiser_projects:
    title: Advertiser
    slug: advertiser
  publisher_projects:
    title: Publisher
    slug: publisher

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Default font sizes
maintext_fontsize: 16px
maintext_lists_fontsize: 16px
mainmenu_fontsize: 15px
sidebar_fontsize: 16px
table_fontsize: 14px

# Color settings (hex-codes without the leading hash-tag)
color:
  darkbrown: 3b302d 
  lightbrown: B2A79D
  lightbrown_background: efedeb
  affilinet_red: ff3f2c
  tangerine: ec5b0a
  tomato: de1c44
  aubergine: 53214b
  berry: 90005b
  yellow: EC810A
  green: 3D7850

